Neos:
  Flow:
    http:
      baseUri: '%env:BASE_URI%'
    security:
      authentication:
        providers:
          CrowdProvider:
            providerOptions:
              crowdApplicationPassword: '%env:CROWD_APPLICATION_PASSWORD%'

  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: 'smtp.mailgun.org'
        port: 2525
        username: '%env:SWIFTMAILER_USERNAME%'
        password: '%env:SWIFTMAILER_PASSWORD%'

  DiscourseCrowdSso:
    ssoSecret: '%env:DISCOURSE_CROWD_SSO%'
    apiKey: '%env:DISCOURSE_API_KEY%'
    apiUsername: '%env:DISCOURSE_API_USERNAME%'

  IdNeosIo:
    crowdApplicationPassword: '%env:CROWD_APPLICATION_PASSWORD%'
